spring:
  datasource:
#    url: jdbc:h2:mem:maindb
    url : jdbc:postgresql://localhost:5432/demo
    username : postgres
    password : 123
  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql
  jpa:
    show-sql: true